name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Проверка среды выполнения
        run: |
          echo "Проверка версии Python:"
          python --version
          echo "Проверка пути pip:"
          which pip
          echo "Проверка версии pip:"
          pip --version
          echo "Проверка переменных окружения:"
          env
      
      - name: Установка Python и pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest  # Явная установка pytest
          python -m pip install pylint  # Явная установка pylint
      
      - name: Проверка установленных пакетов
        run: |
          echo "Список установленных пакетов:"
          pip list
          python -m pytest --version
          python -m pylint --version
      
      - name: Запуск тестов
        run: |
          echo "Запуск тестов..."
          python -m pytest tests  # Явный запуск через python -m
      
      - name: Проверка стиля кода (PEP8)
        run: |
          echo "Запуск проверки кода..."
          python -m pylint main.py
