name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install numpy==1.21.6  # Совместимая версия numpy

      - name: Install Dependencies (DeepPavlov)
        run: |
          source venv/bin/activate
          python -m pip install deeppavlov --no-deps  # Установка без зависимостей
          python -m pip install -r requirements.txt

      - name: Verify Installed Packages
        run: |
          source venv/bin/activate
          python --version
          pip list
          python -m pytest --version
          python -m pylint --version
      
      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          python -m pytest tests  # Явный запуск через python -m
      
      - name: Run Lint (PEP8)
        run: |
          source venv/bin/activate
          python -m pylint main.py
