name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Debugging Environment Setup
        run: |
          set -eux  # Включаем полную отладку
          echo "Проверка версии Python:"
          python --version
          echo "Проверка пути pip:"
          which pip
          echo "Проверка версии pip:"
          pip --version
          echo "Проверка переменных окружения:"
          env
      
      - name: Install Dependencies
        run: |
          set -eux  # Включаем полную отладку
          python -m pip install --upgrade pip setuptools wheel  # Обновление pip, setuptools и wheel
          python -m pip install --upgrade numpy==1.21.6  # Совместимая версия numpy
          python -m pip install -r requirements.txt
      
      - name: Verify Installed Packages
        run: |
          set -eux  # Включаем полную отладку
          python --version
          pip list
          python -m pytest --version
          python -m pylint --version
      
      - name: Run Unit Tests
        run: |
          set -eux  # Включаем полную отладку
          python -m pytest tests  # Явный запуск через python -m
      
      - name: Run Lint (PEP8)
        run: |
          set -eux  # Включаем полную отладку
          python -m pylint main.py
