name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Принудительно используем Python 3.9
      
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel  # Обновление pip, setuptools и wheel
          python -m pip install -r requirements.txt
          python -m pip install pytest  # Устанавливаем pytest
          python -m pip install pylint  # Устанавливаем pylint
      
      - name: Проверка установленных пакетов
        run: |
          python --version
          pip list
          python -m pytest --version
      
      - name: Запуск тестов
        run: |
          python -m pytest tests  # Явный запуск через python -m
      
      - name: Проверка стиля кода (PEP8)
        run: |
          python -m pylint main.py
